### ISSUE TITLE
"HTTP is not supported" error on certain YouTube videos

### ISSUE THREAD

**Issue by iCeParadox64** [wootiown/rxbot#23]
Error is most likely with YoutubeDL. Happens consistently on this video: https://youtu.be/cWcKaTM5jEo

![image](https://user-images.githubusercontent.com/25655781/61827641-11feff00-ae33-11e9-92c4-cb89c0f59325.png)

**Comment by gcfrxbots** [comment]
Unable to recreate, presumed fixed with ytdl.
