### ISSUE TITLE
Error when using "quit" command in bot window

### ISSUE THREAD

**Issue by iCeParadox64** [wootiown/rxbot#29]
![quit](https://user-images.githubusercontent.com/25655781/65785829-43da5d80-e123-11e9-8b7c-efc3fb045e7c.png)

**Comment by gcfrxbots** [comment]
Is only a problem because there's no music playing.  I'll throw in an error catcher to stop it from crashing

**Comment by gcfrxbots** [comment]
Solved in newest release
